### ISSUE TITLE
Opening picker using button insted of input element

### ISSUE THREAD

**Issue by lifecracker87** [thedatepicker/thedatepicker#1]
Hi,
I have a input element **a** & button **b**
<pre><input id="a"> & a button <img src="" id="b"></pre>
`<script>
var datepicker = new TheDatepicker.Datepicker(document.getElementById('a'));
datepicker.options.setFirstDayOfWeek(0);
datepicker.options.setInputFormat('m/d/Y');
datepicker.render();
document.getElementById('b').onclick=function(){datepicker.open()};
</script>`
This works perfectly fine, but my requirement is that when i click on element **a** the date picker must not show.
How can i achieve this.
Thanks in advance for helping me out.

**Comment by VladaHejda** [comment]
```html
<input type="text" id="a">
<button id="b">click</button>
```

```js
var datepicker = new TheDatepicker.Datepicker(document.getElementById('b'));
datepicker.options.setInputFormat('m/d/Y');
datepicker.options.onSelect(function (event, day) {
	document.getElementById('a').value = this.getSelectedDateFormatted();
});
datepicker.render();
```
