### ISSUE TITLE
Option to animate open and close

### ISSUE THREAD

**Issue by aloayzab88** [thedatepicker/thedatepicker#10]
This isn't a problem per se, but is there any possibility of adding an option to animate the opening and closing of the datepicker?
I think this will improve the UX, especially for mobile users, as a smooth transition will be better at communicating the opening and closing of the picker.
I was using this to animate the opening and  closing:
```
picker.options.onOpen((event) => {
    event.target.classList.add('is-open');
    const datepickerContainer = event.target.closest('.some-container').querySelector('.the-datepicker__container');
    datepickerContainer.animate(
        { opacity: [0, 1] },
        { duration: 300 }
    );
});
```
```
picker.options.onClose(() => {
    const inputOpen = document.querySelector('#picker.is-open');
    const datepickerContainer = inputOpen.closest('.some-container').querySelector('.the-datepicker__container');

    const datepickerMain = inputOpen.closest('.some-container'').querySelector('.the-datepicker__main');
    datepickerMain.style.display = 'block';
    const animation = datepickerContainer.animate(
        { opacity: [1, 0] },
        { duration: 300 }
    );
    animation.onfinish = () => {
        datepickerMain.style.display = 'none'
    }
});
```

**Comment by VladaHejda** [comment]
Actually there is a wip branch implementing opening/closing animation https://github.com/thedatepicker/thedatepicker/tree/dev-animate-dp2
However it's not completed yet, and it's not my priority now.

**Comment by aloayzab88** [comment]
thanks, I didn't know about that I will close this issue.
