### ISSUE TITLE
How could I set the input date format as 23 Aug 2020?

### ISSUE THREAD

**Issue by dannyvelas** [thedatepicker/thedatepicker#3]
This is a great library. Thank you for writing it.

How could I get the input date as 23 Aug 2020, instead of  23. 8. 2020. ?

I tried playing with `option.setInputFormat` but it doesn't seem like this format is available.

**Comment by VladaHejda** [comment]
Datepicker for now does not have short form of textual month representation. But you can use a trick with translator:

```js
datepicker.options.setInputFormat('j F Y');
datepicker.options.translator.setMonthTranslation(TheDatepicker.Month.August, 'Aug');
```

You should set other months translations similarly.

Fyi other formatters can be found here: https://github.com/thedatepicker/thedatepicker/blob/master/src/DateConverter.ts#L139
